cmake_minimum_required(VERSION 3.22.1)
project(vybe_recognition LANGUAGES C CXX)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(FFT_LIB kissfft CACHE STRING "" FORCE)
set(KISSFFT_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/chromaprint/src/3rdparty/kissfft" CACHE PATH "" FORCE)
set(KISSFFT_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/chromaprint/src/3rdparty/kissfft" CACHE PATH "" FORCE)
set(USE_INTERNAL_AVRESAMPLE ON CACHE BOOL "" FORCE)
add_subdirectory(chromaprint)
add_library(vybe_recognition SHARED recognition_jni.cpp)
target_include_directories(vybe_recognition PRIVATE chromaprint/src chromaprint/src/include)
target_link_libraries(vybe_recognition PRIVATE chromaprint c++_static c++abi log)
