
const root=document.documentElement,body=document.body;
const themeToggle=document.getElementById('themeToggle'),menuButton=document.getElementById('menuButton'),mobileNav=document.getElementById('mobileNav'),topbar=document.querySelector('.topbar'),fab=document.getElementById('backToTop'),toast=document.getElementById('toast');
const savedTheme=localStorage.getItem('vybe-theme');root.dataset.theme=savedTheme||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
function updateThemeMeta(){document.querySelector('meta[name="theme-color"]')?.setAttribute('content',root.dataset.theme==='dark'?'#1E1234':'#F7F2FF');const icon=themeToggle?.querySelector('[data-theme-icon]');if(icon)icon.innerHTML=root.dataset.theme==='dark'?'<path d="M12 2.75V5m0 14v2.25M4.75 12H2.5m19 0h-2.25M5.6 5.6 4 4m16 16-1.6-1.6M18.4 5.6 20 4M4 20l1.6-1.6M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10Z"/>':'<path d="M12.5 2.2a9.8 9.8 0 1 0 9.3 13 8.2 8.2 0 0 1-9.3-13Z"/>'}updateThemeMeta();
themeToggle?.addEventListener('click',e=>{ripple(e.currentTarget,e);const swap=()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('vybe-theme',root.dataset.theme);updateThemeMeta()};document.startViewTransition?document.startViewTransition(swap):swap()});
function ripple(el,event){const r=el.getBoundingClientRect(),s=document.createElement('span'),size=Math.max(r.width,r.height);s.className='ripple';s.style.width=s.style.height=`${size}px`;s.style.left=`${(event?.clientX||r.left+r.width/2)-r.left}px`;s.style.top=`${(event?.clientY||r.top+r.height/2)-r.top}px`;el.appendChild(s);setTimeout(()=>s.remove(),620)}
document.querySelectorAll('.button,.icon-button,.menu-button,.quick-link,.material-fab').forEach(el=>el.addEventListener('pointerdown',e=>ripple(el,e)));
menuButton?.addEventListener('click',()=>{const open=mobileNav?.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(Boolean(open)))});document.addEventListener('click',e=>{if(!mobileNav?.classList.contains('open'))return;if(mobileNav.contains(e.target)||menuButton?.contains(e.target))return;mobileNav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')});
const current=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('[data-nav]').forEach(a=>{const href=a.getAttribute('href');if(href===current||(current===''&&href==='index.html'))a.classList.add('active')});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -20px'});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
addEventListener('scroll',()=>{topbar?.classList.toggle('scrolled',scrollY>20);fab?.classList.toggle('show',scrollY>650)},{passive:true});fab?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const visual=document.querySelector('[data-parallax]');if(visual&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&matchMedia('(pointer:fine)').matches){visual.addEventListener('pointermove',e=>{const r=visual.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;visual.querySelectorAll('.phone').forEach((p,i)=>{const d=(i+1)*3;p.style.marginLeft=`${x*d}px`;p.style.marginTop=`${y*d}px`})});visual.addEventListener('pointerleave',()=>visual.querySelectorAll('.phone').forEach(p=>{p.style.marginLeft='';p.style.marginTop=''}))}
const api='https://api.github.com/repos/anshdeepofficial/VYBE/releases/latest',fallback='https://github.com/anshdeepofficial/VYBE/releases/latest';
const humanSize=b=>Number.isFinite(b)?`${(b/1024/1024).toFixed(1)} MB · ARM64 APK`:'ARM64 APK';const formatDate=v=>v?new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(v)):'Latest stable release';
async function hydrateRelease(){try{const response=await fetch(api,{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error(`GitHub API ${response.status}`);const release=await response.json(),version=release.tag_name||'Latest',assets=Array.isArray(release.assets)?release.assets:[],arm64=assets.find(a=>/arm64|arm64-v8a/i.test(a.name)&&/\.apk$/i.test(a.name))||assets.find(a=>/\.apk$/i.test(a.name)),url=arm64?.browser_download_url||release.html_url||fallback;document.querySelectorAll('[data-download]').forEach(a=>a.href=url);document.querySelectorAll('[data-version]').forEach(el=>el.textContent=version);const set=(id,t)=>{const el=document.getElementById(id);if(el)el.textContent=t};set('apkSize',humanSize(arm64?.size));set('releaseDate',formatDate(release.published_at));set('assetName',arm64?.name||'Latest APK');set('releaseNotes',release.body||'Latest stable VYBE release.');document.querySelectorAll('script[type="application/ld+json"]').forEach(script=>{try{const data=JSON.parse(script.textContent);if(Array.isArray(data['@type'])&&data['@type'].includes('SoftwareApplication')){data.softwareVersion=version.replace(/^v/i,'');data.downloadUrl=url;script.textContent=JSON.stringify(data)}}catch{}})}catch(error){document.querySelectorAll('[data-download]').forEach(a=>a.href=fallback);console.info('Using release fallback',error.message)}}hydrateRelease();
const faqSearch=document.getElementById('faqSearch');faqSearch?.addEventListener('input',()=>{const q=faqSearch.value.trim().toLowerCase();document.querySelectorAll('.faq-item').forEach(item=>{const match=item.textContent.toLowerCase().includes(q);item.classList.toggle('hidden',!match);if(q&&match)item.open=true})});
